### ISSUE TITLE
I want to join DaalBot team

### ISSUE THREAD

**Issue by kentaurse** [DaalBot/API#1]
As a dedicated developer with extensive expertise in JavaScript, I am enthusiastic about the opportunity to contribute to DaalBot's projects. My experience includes API development, website creation, and building free and open-source Discord bots, making me well-suited to enhance DaalBot's innovative initiatives and drive impactful solutions.

**Comment by NotPiny** [comment]
Hey :sweat_smile: 

I somehow only saw this now and i appreciate the gesture but we're not exactly looking for new team members right now. However if you want to shoot a few suggestions you can either use the issues tab on the repos (if i see them) or the [discord server](https://go.daalbot.xyz/HQ) where i am online a lot more.
